import { createClient } from '@supabase/supabase-js'

const supabaseUrl = 'https://https://qsajvllpyuodipjxxzlf.supabase.co.supabase.co'
const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzYWp2bGxweXVvZGlwanh4emxmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1MzEzNzUsImV4cCI6MjA2MzEwNzM3NX0.3Bu2Z4h9G0ReJcDCn_-ydnOJetWXSJhtjgP44Ixvb3o.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2cnp0bXp4d3p4dnRncG5yaW5tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDUyMDc2MTMsImV4cCI6MjAyMDc4MzYxM30.Dlu3IHHtj9knDmvn5TiX38zGeaSK9Uw7IBK--NBvzYA'
export const supabase = createClient(supabaseUrl, supabaseKey)